### ISSUE TITLE
Unable to find module auth

### ISSUE THREAD

**Issue by silverandrew** [ejmurra/salaryGuide#7]
I get the below error message after following the instructions and running gulp dev: [stdError.txt](https://github.com/ejmurra/salaryGuide/files/139697/stdError.txt)

I tried adding auth on as another dependency (and npm installs the auth module into the node_modules folder) but that didn't resolve the issue.

**Comment by silverandrew** [comment]
My solution to the error: 
1) Install auth as a dependency
2) go into controllers/api directory
3) Edit departments.js, details.js, and search.js to use 'auth.js' instead of '../../auth.js'

**Comment by ejmurra** [comment]
auth.js isn't included in the project as it has details that shouldn't be shared on git. Instead, auth.example.js is included in the base directory. To use the project, change auth.example.js to export your connection string and rename the file to auth.js. You shouldn't have to change paths on any of the controllers and I would argue that auth.js should remain in the project root so that it is easier to swap out with different database servers if necessary.

Docs updated with commit 5351d3638d405977922fd3fa312a6b54f048cd18
